package:
  name: namix
  version: 0.0.1a

source:
  path: .
  # git-url: https://github.com/DLR-VF/NaMIx

build:
  number: 0

requirements:
  build:
    - python
    - setuptools

  run:
    - python
    - osmnx>=1.5.0
    - networkx>=2.5
    - numpy>=1.20
    - Shapely>=2.0
    - geopandas>=0.12
    - rasterio>=1.3
    - pandas>=1.5
    - dask==2023.7.1
    - gtfs-functions==2.0.4

test:
  source_files:
    - tests/test_namix.py

about:
  home: https://github.com/DLR-VF/NaMIx
  license: Eclipse Public License
